website/music/urls.py
from django.conf.urls import url
from . import views



app_name = 'music'

urlpatterns = [


    # /music/ListView
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^songs/$', views.SongListView.as_view(), name='song-list'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    # /music/DetailsView
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='detail'),
    # /music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    # /music/album/2
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    # /music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    # /music/2/fav
    url(r'^album/(?P<pk>[0-9]+)/favorite/$', views.AlbumFavorite.as_view(), name='album-favorite'),

    url(r'^album/song/(?P<pk>[0-9]+)/songfavorite/$', views.SongFavorite.as_view(), name='song-favorite'),

    # /music/album/2/song_add
    url(r'album/(?P<pk>[0-9]+)/song/addsong/$', views.SongCreate.as_view(), name='song-add'),

    url(r'album/song/(?P<pk>[0-9]+)/$', views.SongUpdate.as_view(), name='song-update'),
    # /music/album/2/song/delete
    url(r'album/song/(?P<pk>[0-9]+)/deletesong/$', views.SongDelete.as_view(), name='song-delete'),

    url(r'album/song/listen/(?P<pk>[0-9]+)/$', views.SongPlayer.as_view(), name='song-listen'),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from music.forms import LoginForm
from music.views import UserFormView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
    url(r'^register/$', UserFormView.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator



class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=550)
    genre = models.CharField(max_length=150)
    album_logo = models.ImageField(upload_to='images', blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + '-' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file = models.FileField(upload_to='music', validators=[FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'wma'])])
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.album.pk})

website/music/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))

website/music/views.py
import operator
from django.db.models import Q
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from .models import Album
from .models import Song
from django.views.generic import View
from .forms import UserForm
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):

    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    ordering = ['album_title']

    def get_queryset(self):

        return Album.objects.filter(owner=self.request.user)


@method_decorator(login_required, name='dispatch')
class SongListView(generic.ListView):

    template_name = 'music/song_list.html'
    context_object_name = 'songs'
    ordering = ['title']

    def get_queryset(self):

        return Song.objects.filter(album__owner=self.request.user)



@method_decorator(login_required, name='dispatch')
class DetailsView(generic.DetailView):
    model = Album
    template_name = 'music/details.html'

    def get_queryset(self):

        return Album.objects.filter(owner=self.request.user)


@method_decorator(login_required, name='dispatch')
class SearchView(generic.ListView):
    template_name = 'music/song_list.html'
    context_object_name = 'songs'
    ordering = ['title']

    def get_queryset(self):
        if self.request.GET.get('q'):
            que = self.request.GET['q']
            print(que)
        else:
            return Song.objects.filter(album__owner=self.request.user)
        return Song.objects.filter(album__owner=self.request.user, song_title__startswith=que)


@method_decorator(login_required, name='dispatch')
class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        self.object = obj
        obj.save()
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required, name='dispatch')
class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']
    template_name_suffix = '_update_form'


@method_decorator(login_required, name='dispatch')
class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


@method_decorator(login_required, name='dispatch')
class SongCreate(CreateView):
    model = Song
    fields = ['song_title', 'file']

    def form_valid(self, form):
        obj = form.save(commit=False)
        new2 = self.kwargs['pk']
        obj.album = Album.objects.get(id=new2)
        self.object = obj
        obj.save()
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required, name='dispatch')
class SongUpdate(UpdateView):
    model = Song
    fields = ['song_title', 'file']
    template_name_suffix = '_update_form'


@method_decorator(login_required, name='dispatch')
class SongDelete(DeleteView):
    model = Song

    def get_queryset(self):

        return Song.objects.filter(album__owner=self.request.user)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        new2 = self.object.album.pk
        self.object.delete()
        return HttpResponseRedirect(reverse('music:detail', kwargs={'pk': new2}))


@method_decorator(login_required, name='dispatch')
class AlbumFavorite(View):

    def dispatch(self, request, *args, **kwargs):
        album = Album.objects.get(pk=self.kwargs['pk'])
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()

        return redirect('music:index')


@method_decorator(login_required, name='dispatch')
class SongPlayer(generic.DetailView):
    model = Song
    template_name = 'music/music_player.html'

    def get_queryset(self):

        return Song.objects.filter(album__owner=self.request.user)


@method_decorator(login_required, name='dispatch')
class SongFavorite(View):

    def dispatch(self, request, *args, **kwargs):
        song = Song.objects.get(pk=self.kwargs['pk'])
        new2 = song.album.pk
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()

        return HttpResponseRedirect(reverse('music:detail', kwargs={'pk': new2}))


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):

        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # clean (normalized) data

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return user objects if credentials are correct

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:

                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                    </div>
                </form>


            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

website/music/templates/music/album_update_form.html
{% extends 'music/base.html' %}
{% block title %}Update Album{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </div>
                </form>


            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    <!-- path to ur static -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <link href="{% static 'music/bootstrap3_player1.css' %}?1" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>

</head>
<body>
<nav class="navbar navbar-inverse  navbar-static-top">
    <div class="container-fluid">

        <!--header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- logo -->
            <a class="navbar-brand"  href="{% url 'music:index' %}" style="font-family:'Satisfy',cursive" >Viberr</a>
        </div>

        <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'music:song-list' %}">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="" placeholder="Search Songs">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
                    </a>
                </li>
                <li class="">
                    <a href="/logout">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

website/music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}
{% load staticfiles %}
{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <img src='{% static "images/mus.png" %}' class='img-responsive' alt='Image not found' />
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }}
                        <small>{{ album.genre }}</small>
                    </h1>
                    <h2>{{ album.artist }}</h2>
                    <form action="{% url 'music:album-update' album.id %}" >
                                {% csrf_token %}

                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                    </form>


                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:song-add' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a  href="{% url 'music:song-listen' song.id %}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:song-favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star text-muted {% if song.is_favorite %}text-primary active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <!-- delete modal trigger -->
                                    <button type="button" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#myModal" data-id="{{ album.id }}">
                                        <span class="glyphicon glyphicon-remove"></span>  Delete
                                    </button>
                                </td>
                                <td>
                                    <form action="{% url 'music:song-update' song.id %}" >
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            <!-- Delete Modal -->
                             <div id="myModal" class="modal fade" role="dialog">
                                  <div class="modal-dialog">

                                    <!-- Modal content-->
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title">Delete Song</h4>
                                      </div>
                                      <div class="modal-body">
                                          <h3>Are you sure you want to delete this Album</h3>
                                          <form action="{% url 'music:song-delete' song.id%}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="song_id" value="{{ song.id }}" />
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                          </form>

                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                      </div>
                                    </div>

                                  </div>
                             </div>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div >
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

website/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block albums_active %}active{% endblock %}
{% load staticfiles %}
{{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
        </div>
        {% if all_albums %}
            {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail" >

                        {% if album.album_logo %}
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive" alt="Image not found" width="185" height="185"  />
                        </a>
                        {% else  %}
                        <a href="{% url 'music:detail' album.id %}">
                            <img src='{% static "images/mus.png" %}' class='img-responsive' alt='Image not found' />
                        </a>
                        {% endif %}

                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- delete modal trigger -->
                            <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#myModal" data-id="{{ album.id }}"><span class="glyphicon glyphicon-trash"></span></button>

                            <!-- Favorite Album -->
                            <a href="{% url 'music:album-favorite' album.id %}" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star  {% if album.is_favorite %}text-primary active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>

                <!-- Delete Modal -->
                <div id="myModal" class="modal fade" role="dialog">
                  <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Delete Album</h4>
                      </div>
                      <div class="modal-body">
                          <h3>Are you sure you want to delete this Album</h3>
                          <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                              {% csrf_token %}
                              <input type="hidden" name="album_id" value="{{ album.id }}" />
                              <button type="submit" class="btn btn-danger btn-sm">
                                  Delete
                              </button>
                          </form>

                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      </div>
                    </div>

                  </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>




</div>


{% endblock %}

website/music/templates/music/music_player.html
{% extends 'music/base.html' %}

{% block title %}{{ song }}{% endblock %}
{% block albums_active %}active{% endblock %}
{% load staticfiles %}

{{% block body %}

<div class="container-fluid ">
    <div class="row col-md-8 col-md-offset-2 col-xs-12">
        <audio controls

                  data-info-album-art="{% if song.album.album_logo %}{{ album.album_logo.url }}{% else %}{% static 'images/mus.png' %}{% endif %}"
                  data-info-album-title="{{ song.album.album_title }}"
                  data-info-artist="{{ song.album.artist }}"
                  data-info-title="{{ song.song_title }}">



                  <source src="{{ song.file.url }}" type="audio/mpeg" />
                  <a href="{{ song.file.url }}">{{ song.song_title }}</a>
                  An html5-capable browser is required to play this audio.
        </audio>
    </div>
    <script src="{% static 'music/js/bootstrap3_player1.js' %}?1"></script>
</div>

{% endblock %}

website/music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Add</button>
                        </div>
                    </div>
                </form>


            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}

website/music/templates/music/song_list.html
{% extends 'music/base.html' %}
{% block songs_active %}active{% endblock %}

{{% block body %}

<div class="albums-container container-fluid">

      <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a  href="{% url 'music:song-listen' song.id %}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                {% if album.album_logo %}
                                                    <img src="{{ album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;">
                                                {% else %}
                                                    {% load static from staticfiles %}
                                                    <img src='{% static "images/mus.png" %}' class='img-responsive' alt='Image not found' style="width: 20px; float: left; margin-right: 10px;" />
                                                {% endif %}
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:song-favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star text-muted {% if song.is_favorite %}text-primary active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="row">
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album with Your Desired Songs
                    </button>
                </a>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

website/music/templates/music/song_update_form.html
{% extends 'music/base.html' %}
{% block title %}Update Song{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
        <div class="panel panel-default">
            <div class="panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </div>
                </form>


            </div>
        </div>
        </div>
    </div>
</div>
{% endblock %}