website/music/urls.py
from django.conf.urls import url
from . import views



app_name = 'music'

urlpatterns = [


    # /music/ListView
    url(r'^$', views.IndexView.as_view(), name='index'),

    url(r'^songs/$', views.SongListView.as_view(), name='song-list'),

    url(r'^search/$', views.SearchView.as_view(), name='search'),

    # /music/DetailsView
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='detail'),
    # /music/album/add
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    # /music/album/2
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    # /music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    # /music/2/fav
    url(r'^album/(?P<pk>[0-9]+)/favorite/$', views.AlbumFavorite.as_view(), name='album-favorite'),

    url(r'^album/song/(?P<pk>[0-9]+)/songfavorite/$', views.SongFavorite.as_view(), name='song-favorite'),

    # /music/album/2/song_add
    url(r'album/(?P<pk>[0-9]+)/song/addsong/$', views.SongCreate.as_view(), name='song-add'),

    url(r'album/song/(?P<pk>[0-9]+)/$', views.SongUpdate.as_view(), name='song-update'),
    # /music/album/2/song/delete
    url(r'album/song/(?P<pk>[0-9]+)/deletesong/$', views.SongDelete.as_view(), name='song-delete'),

    url(r'album/song/listen/(?P<pk>[0-9]+)/$', views.SongPlayer.as_view(), name='song-listen'),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from music.forms import LoginForm
from music.views import UserFormView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}),
    url(r'^register/$', UserFormView.as_view(), name='register'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Login{% endblock %}</title>
    <!-- path to ur static -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
</head>
<body>
<nav class="navbar navbar-inverse  navbar-static-top">
    <div class="container-fluid">

        <!--header-->
        <div class="navbar-header">

            <a class="navbar-brand"  href="{% url 'music:index' %}" style="font-family:'Satisfy',cursive" >Viberr</a>
        </div>


    </div>
</nav>
{% block content %}

{% endblock %}
 <!-- Core Scripts - Include with every page -->
<script src = "{% static 'js/jquery.min.js' %}"></script>
<script src = "{% static 'js/bootstrap.min.js' %}"></script>
{% block javascript %}
{% endblock %}
</body>
</html>

website/templates/login.html
{% extends 'base.html' %}


{% block content %}
{% if form.errors %}

<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}

<h3>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</h3>
    {% endif %}

<h3>Please login to see this page.</h3>

{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-inverse">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    <form method="post" action="">
{% csrf_token %}

                        <p class="bs-component">
                            <table>
                                <tr>
                                    <td>{{ form.username.label_tag }}</td>
                                    <td>{{ form.username }}</td>
                                </tr>
                                <tr>
                                    <td>{{ form.password.label_tag }}</td>
                                    <td>{{ form.password }}</td>
                                </tr>
                            </table>
                        </p>
                        <p class="bs-component">
                            <center>
                                <input class="btn btn-success btn-sm" type="submit" value="login" />
                            </center>
                        </p>
                        <input type="hidden" name="next" value="{{ next }}" />
                    </form>
                </div>
                <h6>Don't have an account,<a href="http://127.0.0.1:8000/register/">Register</a></h6>
            </div>

        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}


<script>
{% if not user.is_authenticated %}
$("ul.nav.navbar-nav.navbar-right").css("display","none");
{% endif %}
</script>

{% endblock %}